### ISSUE TITLE
issues writing to HBase version 0.94.2-cdh4.2.0

### ISSUE THREAD

**Issue by avihoo** [nerdammer/spark-hbase-connector#16]
I'm trying to write to HBase version 0.94.2-cdh4.2.0 using Scala and Spark.

I'm not getting any error but these messages: 
```scala
INFO  2015-11-02 15:50:54,285 [Executor task launch worker-1-SendThread(host:2181)] org.apache.zookeeper.ClientCnxn: Opening socket connection to server ip/ip:2181. Will not attempt to authenticate using SASL (unknown error)
INFO  2015-11-02 15:50:54,453 [Executor task launch worker-1-SendThread(host:2181)] org.apache.zookeeper.ClientCnxn: Socket connection established to host/host:2181, initiating session
[Stage 0:>                                                          (0 + 4) / 4]INFO  2015-11-02 15:50:54,627 [Executor task launch worker-1-SendThread(host:2181)] org.apache.zookeeper.ClientCnxn: Session establishment complete on server host/host:2181, sessionid = 0x150608c04de044c, negotiated timeout = 90000
INFO  2015-11-02 15:50:55,287 [Executor task launch worker-1] org.apache.hadoop.hbase.mapreduce.TableOutputFormat: Created table instance for testTable
INFO  2015-11-02 15:50:55,324 [Executor task launch worker-2] org.apache.hadoop.hbase.mapreduce.TableOutputFormat: Created table instance for testTable
INFO  2015-11-02 15:50:55,325 [Executor task launch worker-3] org.apache.hadoop.hbase.mapreduce.TableOutputFormat: Created table instance for testTable
INFO  2015-11-02 15:50:55,326 [Executor task launch worker-0] org.apache.hadoop.hbase.mapreduce.TableOutputFormat: Created table instance for testTable
```

Is there any known issue with writing to that specific version of HBase?

**Comment by xiaolezhu** [comment]
I tried using two ways to write to hbase:
1.  standard spark hbase API saveAsNewAPIHadoopDataset. 
2.  use spark-hbase-connector.

They both failed with the same issue that it was hanging there after "Created table instance for testTable" without any error messages:

**Log**
16/03/24 23:26:00 INFO ClientCnxn: Session establishment complete on server bpaascp1devhbasezk01.bpaas.local/192.168.23.33:2181, sessionid = 0x152844be97f6ddf, negotiated timeout = 40000
16/03/24 23:26:00 INFO ZooKeeperRegistry: **ClusterId read in ZooKeeper is null**
16/03/24 23:26:00 INFO TableOutputFormat: Created table instance for testTable

By looking into the log closely -  there is one more line of Log says:  **ClusterId read in ZooKeeper is null**. The issue is because that **zookeeper.znode.parent ** was not set with proper value - **zookeeper.znode.parent ** tells which znode keeps the data (and address for HMaster) for the cluster.

The value of zookeeper.znode.parent in HBASE_CONF/hbase-site.xml. After I set the proper value into HBaseConfiguration, the issue was gone by using saveAsNewAPIHadoopDataset.

However, in spark-hbase-connector there will need to be code changed to set value of zookeeper.znode.parent, similar to how spark.hbase.host is set.

**Comment by avihoo** [comment]
I'm afraid I don't have the `zookeeper.znode.parent` property set in my `HBASE_CONF/hbase-site.xml`.
What should I do in order to make it still save from spark to hbase?

**Comment by nicolaferraro** [comment]
Version 1.0.3 of the connector (already available on maven) supports the hbase-site.xml file for specifying a custom configuration.

**Comment by xiaolezhu** [comment]
Great to know :)
