### ISSUE TITLE
Optimizations on Spark HBase connector

### ISSUE THREAD

**Issue by mkanchwala** [nerdammer/spark-hbase-connector#29]
Hey Guys,

I was wondering what kind of optimizations can I perform to improve my speed for Read and Write on HBase. Is there any documentation or steps present for it.

For e.g.

1) Partition Discovery or Some kind of Region / Key based optimizations internally handling the read or scan operations
2) Some memory management parameters which could improve the read write speed. etc

**Comment by nicolaferraro** [comment]
For super-fast reading of HBase data, take a look at https://github.com/unicredit/hbase-rdd#bulk-load-to-hbase-using-hfiles. They started trying to optimize writing by accessing HFiles directly.

**Comment by mkanchwala** [comment]
Is there any optimizations we can do here itself? I don't want to switch to the other one.

**Comment by nicolaferraro** [comment]
There are no tuning parameter currently in this lib, so you can optimize read/write access by designing your data store according to the needs of your application. For example, using [salting prefixes](https://github.com/nerdammer/spark-hbase-connector#salting-prefixes) for time series data is a good practice, to prevent hot-spotting when writing and use all the cluster resources when reading. Other options include partitioning your RDDs by (alphabetical) range of row key, instead of normal Spark hashing, to optimize write performance.

Other kind of optimizations can be done at HBase driver level by providing a `hbase-site.xml` file. This library uses it under the hood. Refer to the [HBase documentation](https://hbase.apache.org/book.html).

For the memory management and scheduling part, refer to the spark doc (especially the [YARN section](http://spark.apache.org/docs/latest/running-on-yarn.html), if you're using YARN).
